// ============================================================
// components/MomDisplay.jsx — Minutes of Meeting Display
// ============================================================
// Renders the EXACT 6-field structure returned by your ML model:
//   1. Date, Time & Venue
//   2. Attendees
//   3. Agenda
//   4. Summary  (your model generates this — shown prominently)
//   5. Decisions Taken
//   6. Action Items (Task + Owner + Deadline)
//   7. Next Meeting Date
//
// Also includes a Download MoM button at the bottom using
// the browser Blob API — zero external libraries.
//
// PROPS:
//   momData — the full meeting object from your ML model
//   isDark  — boolean for dark/light theme styling
// ============================================================

// ── Theme helper ─────────────────────────────────────────────
// Returns the right Tailwind class depending on dark/light mode.
// Used throughout to avoid repeating long ternary expressions.
const t = (isDark, darkClass, lightClass) => isDark ? darkClass : lightClass;

// ── Sub-component: Section wrapper ──────────────────────────
function Section({ title, icon, isDark, children }) {
  return (
    <div className="mb-6">
      <div className="flex items-center gap-2 mb-3">
        <span className="text-base">{icon}</span>
        <h3 className={`text-xs font-semibold uppercase tracking-widest
          ${t(isDark, "text-slate-400", "text-slate-500")}`}>
          {title}
        </h3>
      </div>
      {children}
    </div>
  );
}

// ── Sub-component: Bullet list item ─────────────────────────
function BulletItem({ children, isDark, accent = "indigo" }) {
  const dotColor = accent === "emerald" ? "bg-emerald-500"
                 : accent === "violet"  ? "bg-violet-500"
                 : "bg-indigo-500";
  return (
    <li className="flex items-start gap-3 py-1.5">
      <span className={`mt-2 w-1.5 h-1.5 rounded-full shrink-0 ${dotColor}`}/>
      <span className={`text-sm leading-relaxed ${t(isDark, "text-slate-300", "text-slate-600")}`}>
        {children}
      </span>
    </li>
  );
}

// ── Sub-component: "NOT AVAILABLE" badge ────────────────────
// Your ML model returns "NOT AVAILABLE" for missing fields.
// We render these as a styled badge instead of plain text.
function NotAvailable({ isDark }) {
  return (
    <span className={`inline-flex items-center gap-1.5 text-xs px-2.5 py-1 rounded-full font-medium
      ${t(isDark,
        "bg-slate-800 text-slate-500 border border-slate-700",
        "bg-slate-100 text-slate-400 border border-slate-200")}`}>
      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 12H4"/>
      </svg>
      Not Available
    </span>
  );
}

// ── Download helper ──────────────────────────────────────────
// Uses the Blob + URL.createObjectURL browser API to generate
// a formatted .txt file and trigger an instant download.
function downloadMoM(momData) {
  const sep  = "═══════════════════════════════════════════";
  const line = "───────────────────────────────────────────";
  const na   = (v) => (!v || v === "NOT AVAILABLE") ? "Not Available" : v;
  const list = (arr) => !arr || arr.length === 0
    ? "  Not Available"
    : arr.map((i) => `  • ${i}`).join("\n");

  const content = [
    sep, "  MINUTES OF MEETING", sep,
    `Title         : ${na(momData.title)}`,
    `Date & Time   : ${na(momData.dateTimeVenue)}`,
    `Venue         : ${na(momData.venue)}`,
    "",
    line, "ATTENDEES", line,
    list(momData.attendees),
    "",
    line, "AGENDA", line,
    list(momData.agenda),
    "",
    line, "SUMMARY", line,
    `  ${na(momData.summary)}`,
    "",
    line, "DECISIONS TAKEN", line,
    list(momData.decisions),
    "",
    line, "ACTION ITEMS", line,
    ...(momData.actionItems || []).map((item, i) =>
      `  ${i+1}. ${item.task}\n     Owner: ${na(item.owner)}  |  Deadline: ${na(item.deadline)}`
    ),
    "",
    line, "NEXT MEETING", line,
    `  ${na(momData.nextMeeting)}`,
    "",
    sep, "  Generated by Meeting Summarizer", sep,
  ].join("\n");

  const blob = new Blob([content], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `MoM_${(momData.title || "Meeting").replace(/\s+/g, "_")}.txt`;
  a.click();
  URL.revokeObjectURL(url); // Free memory after download
}

// ── Main component ───────────────────────────────────────────
export default function MomDisplay({ momData, isDark }) {
  if (!momData) return <p className={`text-sm ${t(isDark, "text-slate-500", "text-slate-400")}`}>No data available.</p>;

  // Helper: returns true if a field has real content (not "NOT AVAILABLE")
  const hasValue = (v) => v && v !== "NOT AVAILABLE";

  const {
    title, dateTimeVenue, venue, attendees,
    agenda, summary, decisions, actionItems, nextMeeting,
  } = momData;

  return (
    <div>
      {/* ── MoM Header ── */}
      <div className={`mb-6 pb-5 border-b ${t(isDark, "border-slate-800", "border-slate-200")}`}>
        <h2 className={`text-xl font-bold ${t(isDark, "text-white", "text-slate-900")}`}
          style={{ fontFamily: "'Syne', sans-serif" }}>
          {hasValue(title) ? title : "Meeting Summary"}
        </h2>
        {/* ── FIELD 1: Date, Time, Venue ── */}
        <div className="flex flex-wrap items-center gap-3 mt-2">
          {hasValue(dateTimeVenue) ? (
            <span className={`flex items-center gap-1.5 text-sm ${t(isDark, "text-slate-400", "text-slate-500")}`}>
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"/>
              </svg>
              {dateTimeVenue}
            </span>
          ) : <NotAvailable isDark={isDark}/>}
          {hasValue(venue) && (
            <span className={`flex items-center gap-1.5 text-sm ${t(isDark, "text-slate-400", "text-slate-500")}`}>
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/>
              </svg>
              {venue}
            </span>
          )}
        </div>
      </div>

      {/* ── FIELD 2: Attendees ── */}
      <Section title="Attendees" icon="👥" isDark={isDark}>
        {attendees && attendees.length > 0 ? (
          <div className="flex flex-wrap gap-2">
            {attendees.map((p, i) => (
              <span key={i} className={`text-xs px-3 py-1 rounded-full
                ${t(isDark,
                  "bg-slate-800 border border-slate-700 text-slate-300",
                  "bg-slate-100 border border-slate-200 text-slate-600")}`}>
                {p}
              </span>
            ))}
          </div>
        ) : <NotAvailable isDark={isDark}/>}
      </Section>

      {/* ── FIELD 3: Agenda ── */}
      <Section title="Agenda of the Meeting" icon="📋" isDark={isDark}>
        {agenda && agenda.length > 0
          ? <ul>{agenda.map((item, i) => <BulletItem key={i} isDark={isDark}>{item}</BulletItem>)}</ul>
          : <NotAvailable isDark={isDark}/>
        }
      </Section>

      {/* ── FIELD 4: Summary (generated by your ML model) ── */}
      <Section title="Summary" icon="📝" isDark={isDark}>
        {hasValue(summary) ? (
          <p className={`text-sm leading-relaxed rounded-xl p-4 border
            ${t(isDark,
              "text-slate-300 bg-indigo-500/5 border-indigo-500/15",
              "text-slate-600 bg-indigo-50 border-indigo-100")}`}>
            {summary}
          </p>
        ) : <NotAvailable isDark={isDark}/>}
      </Section>

      {/* ── FIELD 5: Decisions Taken ── */}
      <Section title="Decisions Taken in the Meeting" icon="✅" isDark={isDark}>
        {decisions && decisions.length > 0 ? (
          <ul>{decisions.map((d, i) => <BulletItem key={i} isDark={isDark} accent="emerald">{d}</BulletItem>)}</ul>
        ) : <NotAvailable isDark={isDark}/>}
      </Section>

      {/* ── FIELD 6: Action Items — Task + Owner + Deadline ── */}
      <Section title="Specific Tasks, Responsible Individuals & Deadlines" icon="⚡" isDark={isDark}>
        {actionItems && actionItems.length > 0 ? (
          <div className={`rounded-xl border overflow-hidden ${t(isDark, "border-slate-800", "border-slate-200")}`}>
            {/* Table header */}
            <div className={`grid grid-cols-3 px-4 py-2.5 text-xs font-semibold uppercase tracking-wider
              ${t(isDark, "bg-slate-800/80 text-slate-400", "bg-slate-100 text-slate-500")}`}>
              <span>Task</span><span>Owner</span><span>Deadline</span>
            </div>
            {actionItems.map((item, i) => (
              <div key={i} className={`grid grid-cols-3 px-4 py-3 border-t transition-colors
                ${t(isDark,
                  "border-slate-800 hover:bg-slate-800/40",
                  "border-slate-100 hover:bg-slate-50")}`}>
                <span className={`text-sm pr-2 ${t(isDark, "text-slate-300", "text-slate-700")}`}>{item.task}</span>
                {/* Owner: show badge if NOT AVAILABLE */}
                {hasValue(item.owner)
                  ? <span className={`text-sm ${t(isDark, "text-indigo-400", "text-indigo-600")}`}>{item.owner}</span>
                  : <span><NotAvailable isDark={isDark}/></span>
                }
                {/* Deadline: show badge if NOT AVAILABLE */}
                {hasValue(item.deadline)
                  ? <span className={`text-sm ${t(isDark, "text-amber-400", "text-amber-600")}`}>{item.deadline}</span>
                  : <span><NotAvailable isDark={isDark}/></span>
                }
              </div>
            ))}
          </div>
        ) : <NotAvailable isDark={isDark}/>}
      </Section>

      {/* ── FIELD 7: Next Meeting ── */}
      <Section title="When the Next Meeting Will Be Held" icon="📅" isDark={isDark}>
        {hasValue(nextMeeting) ? (
          <div className={`flex items-center gap-3 rounded-xl px-4 py-3 border
            ${t(isDark,
              "bg-violet-500/8 border-violet-500/20 text-violet-300",
              "bg-violet-50 border-violet-100 text-violet-700")}`}>
            <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>
            <span className="text-sm">{nextMeeting}</span>
          </div>
        ) : <NotAvailable isDark={isDark}/>}
      </Section>

      {/* ── Download Button ── */}
      <div className={`pt-3 mt-2 border-t ${t(isDark, "border-slate-800", "border-slate-200")}`}>
        <button
          onClick={() => downloadMoM(momData)}
          className="w-full flex items-center justify-center gap-2.5 py-3 rounded-xl
            text-sm font-semibold transition-all duration-200"
          style={{
            background: "linear-gradient(135deg, rgba(99,102,241,0.12), rgba(139,92,246,0.08))",
            border: "1px solid rgba(99,102,241,0.25)",
            color: isDark ? "#a5b4fc" : "#6366f1",
            fontFamily: "'Syne', sans-serif",
          }}
          onMouseEnter={e => {
            e.currentTarget.style.background = "linear-gradient(135deg, rgba(99,102,241,0.22), rgba(139,92,246,0.16))";
            e.currentTarget.style.boxShadow  = "0 0 24px rgba(99,102,241,0.2)";
          }}
          onMouseLeave={e => {
            e.currentTarget.style.background = "linear-gradient(135deg, rgba(99,102,241,0.12), rgba(139,92,246,0.08))";
            e.currentTarget.style.boxShadow  = "none";
          }}
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
              d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/>
          </svg>
          Download Minutes of Meeting (.txt)
        </button>
      </div>
    </div>
  );
}
